### ISSUE TITLE
Implement prototype Simplicity interpreter

### ISSUE THREAD

**Issue by jb55** [jb55/btcs#27]
It would be nice to expand the interpreter's ability to handle future upgrades to the Bitcoin script (thanks to segwit). I wonder if there's anything stopping me from implementing Simplicity? /cc @roconnor-blockstream

**Comment by roconnor-blockstream** [comment]
Simplicity will effectively not be sharing any code with Bitcoin Script, so there may be little point in hosting it in the same project.

When it's ready the Simplicity SDK will have a stand-alone C interpreter module you will be able to link with and will hopefully provide everything you will need.  I think you will be better off just waiting.

**Comment by jb55** [comment]
Thanks!
